<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "accommodation"
 *
 * Auto generated by Extension Builder 2016-02-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Accommodation',
	'description' => 'A powerful manager for holiday accommodations reservations.',
	'category' => 'plugin',
	'author' => 'Steve Lenz',
	'author_email' => 'kontakt@steve-lenz.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);